keyboard = '';
$selectedInput = '';

function makeKeyboard() {
    if (!keyboard) {
        keyboard = new window.SimpleKeyboard.default({
            preventMouseDownDefault: false,
            preventMouseUpDefault: false,
            layout: {
                'default': [
                    'β ç ɗ ɖ ð ɟ ɢ ɦ ħ ʜ ɭ ɬ ɮ ʟ ʎ ɱ ɰ ŋ ɳ ɲ ɴ',
                    'ɸ ɹ ɻ ɾ ɽ ʀ ʁ ʂ ʃ θ ʈ ʋ ɣ ʍ χ ʐ ʒ ʔ ʕ ʡ ʢ',
                    'ɑ ɐ ɒ æ ə ɘ ɵ ɚ ɛ ɜ ɝ ɞ ɨ ɪ ɔ ø œ ɶ ɥ ʌ ʊ ʉ ɯ ɤ ʏ',
                    '∅ ˈ ˌ ː ˑ ʼ ʴ ʰ ʱ ʲ ʷ ˠ ˤ',
                    '˞ ̃ ̆ ̈ ̽ ̚ ̋ ́ ̄ ̀ ̏ ̌ ̂ ̊ ̥ ̤ ̪ ̬ ̰ ̺ ̼ ̻ ̹ ̜ ̟ ̠ ̝ ̩ ̞ ̯ ̘ ̙'
                ]
            },
            buttonAttributes: [
                { attribute: "title", buttons: "p", value: "Voiceless Bilabial Plosive", },
                { attribute: "title", buttons: "b", value: "Voiced Bilabial Plosive", },
                { attribute: "title", buttons: "t", value: "Voiceless Alveolar Plosive", },
                { attribute: "title", buttons: "d", value: "Voiced Alveolar Plosive", },
                { attribute: "title", buttons: "ʈ", value: "Voiceless Retroflex Plosive", },
                { attribute: "title", buttons: "ɖ", value: "Voiced Retroflex Plosive", },
                { attribute: "title", buttons: "c", value: "Voiceless Palatal Plosive", },
                { attribute: "title", buttons: "ɟ", value: "Voiced Palatal Plosive", },
                { attribute: "title", buttons: "k", value: "Voiceless Velar Plosive", },
                { attribute: "title", buttons: "ɡ", value: "Voiced Velar Plosive", },
                { attribute: "title", buttons: "q", value: "Voiceless Uvular Plosive", },
                { attribute: "title", buttons: "ɢ", value: "Voiced Uvular Plosive", },
                { attribute: "title", buttons: "ʡ", value: "Epiglottal Plosive", },
                { attribute: "title", buttons: "ʔ", value: "Glottal Stop", },
                { attribute: "title", buttons: "m", value: "Bilabial Nasal", },
                { attribute: "title", buttons: "ɱ", value: "Labiodental Nasal", },
                { attribute: "title", buttons: "n", value: "Alveolar Nasal", },
                { attribute: "title", buttons: "ɳ", value: "Retroflex Nasal", },
                { attribute: "title", buttons: "ɲ", value: "Palatal Nasal", },
                { attribute: "title", buttons: "ŋ", value: "Velar Nasal", },
                { attribute: "title", buttons: "ɴ", value: "Uvular Nasal", },
                { attribute: "title", buttons: "ʙ", value: "Bilabial Trill", },
                { attribute: "title", buttons: "r", value: "Alveolar Trill", },
                { attribute: "title", buttons: "ʀ", value: "Uvular Trill", },
                { attribute: "title", buttons: "ⱱ", value: "Labiodental Flap", },
                { attribute: "title", buttons: "ɾ", value: "Alveolar Tap", },
                { attribute: "title", buttons: "ɽ", value: "Retroflex Flap", },
                { attribute: "title", buttons: "ɸ", value: "Voiceless Bilabial Fricative", },
                { attribute: "title", buttons: "β", value: "Voiced Bilabial Fricative", },
                { attribute: "title", buttons: "f", value: "Voiceless Labiodental Fricative", },
                { attribute: "title", buttons: "v", value: "Voiced Labiodental Fricative", },
                { attribute: "title", buttons: "θ", value: "Voiceless Dental Fricative", },
                { attribute: "title", buttons: "ð", value: "Voiced Dental Fricative", },
                { attribute: "title", buttons: "s", value: "Voiceless Alveolar Sibilant", },
                { attribute: "title", buttons: "z", value: "Voiced Alveolar Sibilant", },
                { attribute: "title", buttons: "ʃ", value: "Voiceless Palato-alveolar Sibilant", },
                { attribute: "title", buttons: "ʒ", value: "Voiced Palato-alveolar Sibilant", },
                { attribute: "title", buttons: "ʂ", value: "Voiceless Retroflex Sibilant", },
                { attribute: "title", buttons: "ʐ", value: "Voiced Retroflex Sibilant", },
                { attribute: "title", buttons: "ç", value: "Voiceless Palatal Fricative", },
                { attribute: "title", buttons: "ʝ", value: "Voiced Palatal Fricative", },
                { attribute: "title", buttons: "x", value: "Voiceless Velar Fricative", },
                { attribute: "title", buttons: "ɣ", value: "Voiced Velar Fricative", },
                { attribute: "title", buttons: "χ", value: "Voiceless Uvular Fricative", },
                { attribute: "title", buttons: "ʁ", value: "Voiced Uvular Fricative", },
                { attribute: "title", buttons: "ħ", value: "Voiceless Pharyngeal Fricative", },
                { attribute: "title", buttons: "ʕ", value: "Voiced Pharyngeal Fricative", },
                { attribute: "title", buttons: "ʜ", value: "Voiceless Epiglottal Fricative", },
                { attribute: "title", buttons: "ʢ", value: "Voiced Epiglottal Fricative", },
                { attribute: "title", buttons: "h", value: "Voiceless Glottal Fricative", },
                { attribute: "title", buttons: "ɦ", value: "Voiced Glottal Fricative", },
                { attribute: "title", buttons: "ɬ", value: "Voiceless Alveolar Lateral Fricative", },
                { attribute: "title", buttons: "ɮ", value: "Voiced Alveolar Lateral Fricative", },
                { attribute: "title", buttons: "ʋ", value: "Labiodental Approximant", },
                { attribute: "title", buttons: "ɹ", value: "Alveolar Approximant", },
                { attribute: "title", buttons: "ɻ", value: "Retroflex Approximant", },
                { attribute: "title", buttons: "j", value: "Palatal Approximant", },
                { attribute: "title", buttons: "ɰ", value: "Velar Approximant", },
                { attribute: "title", buttons: "l", value: "Alveolar Lateral Approximant", },
                { attribute: "title", buttons: "ɭ", value: "Retroflex Lateral Approximant", },
                { attribute: "title", buttons: "ʎ", value: "Palatal Lateral Approximant", },
                { attribute: "title", buttons: "ʟ", value: "Velar Lateral Approximant", },
                { attribute: "title", buttons: "ɺ", value: "Alveolar Lateral Flap", },
                { attribute: "title", buttons: "β", value: "Voiced Bilabial Fricative", },
                { attribute: "title", buttons: "ç", value: "Voiced Palatal Fricative", },
                { attribute: "title", buttons: "i", value: "Close Front Unrounded Vowel", }, 
                { attribute: "title", buttons: "y", value: "Close Front Rounded Vowel", }, 
                { attribute: "title", buttons: "ɨ", value: "Close Central Unrounded Vowel", }, 
                { attribute: "title", buttons: "ʉ", value: "Close Central Rounded Vowel", }, 
                { attribute: "title", buttons: "ɯ", value: "Close Back Unrounded Vowel", }, 
                { attribute: "title", buttons: "u", value: "Close Back Rounded Vowel", }, 
                { attribute: "title", buttons: "ɪ", value: "Near-close Near-front Unrounded Vowel", }, 
                { attribute: "title", buttons: "ʏ", value: "Near-close Near-front Rounded Vowel", }, 
                { attribute: "title", buttons: "ʊ", value: "Near-close Near-back Vowel", }, 
                { attribute: "title", buttons: "e", value: "Close-mid Front Unrounded Vowel", }, 
                { attribute: "title", buttons: "ø", value: "Close-mid Front Rounded Vowel", }, 
                { attribute: "title", buttons: "ɘ", value: "Close-mid Central Unrounded Vowel", }, 
                { attribute: "title", buttons: "ɵ", value: "Close-mid Central Rounded Vowel", }, 
                { attribute: "title", buttons: "ɤ", value: "Close-mid Back Unrounded Vowel", }, 
                { attribute: "title", buttons: "o", value: "Close-mid Back Rounded Vowel", }, 
                { attribute: "title", buttons: "ə", value: "Mid-central Vowel", }, 
                { attribute: "title", buttons: "ɛ", value: "Open-mid Front Unrounded Vowel", }, 
                { attribute: "title", buttons: "œ", value: "Open-mid Front Rounded Vowel", }, 
                { attribute: "title", buttons: "ɜ", value: "Open-mid Central Unrounded Vowel", }, 
                { attribute: "title", buttons: "ɞ", value: "Open-mid Central Rounded Vowel", }, 
                { attribute: "title", buttons: "ʌ", value: "Open-mid Back Unrounded Vowel", }, 
                { attribute: "title", buttons: "ɔ", value: "Open-mid Back Rounded Vowel", }, 
                { attribute: "title", buttons: "æ", value: "Near-open Front Unrounded Vowel", }, 
                { attribute: "title", buttons: "ɐ", value: "Near-open Central Vowel", }, 
                { attribute: "title", buttons: "a", value: "Open Front Unrounded Vowel", }, 
                { attribute: "title", buttons: "ɶ", value: "Open Front Rounded Vowel", }, 
                { attribute: "title", buttons: "ɑ", value: "Open Back Unrounded Vowel", }, 
                { attribute: "title", buttons: "ɒ", value: "Open Back Rounded Vowel", }, 
                { attribute: "title", buttons: "ɚ", value: "R-Colored Mid-Central Vowel", },
                { attribute: "title", buttons: "ʍ", value: "Voiceless Labio-Velar Fricative", },
                { attribute: "title", buttons: "w", value: "Voiced Labio-Velar Approximant", },
                { attribute: "title", buttons: "ɥ", value: "Voiced Labio-Palatal Approximant", },
                { attribute: "title", buttons: "ɫ", value: "Velarized Alveolar Lateral Approximant", },
                { attribute: "title", buttons: "ɓ", value: "Voiced Bilabial Implosive", },
                { attribute: "title", buttons: "ɗ", value: "Voiced Alveolar Implosive", },
                { attribute: "title", buttons: "ᶑ", value: "Voiced Retroflex Implosive", },
                { attribute: "title", buttons: "ʄ", value: "Voiced Palatal Implosive", },
                { attribute: "title", buttons: "ɠ", value: "Voiced Velar Implosive", },
                { attribute: "title", buttons: "ʛ", value: "Voiced Uvular Implosive", },
                { attribute: "title", buttons: "ʘ", value: "Bilabial Click", },
                { attribute: "title", buttons: "ǀ", value: "Dental Click", },
                { attribute: "title", buttons: "ǃ", value: "Alveolar Click", },
                { attribute: "title", buttons: "ǂ", value: "Palatal Click", },
                { attribute: "title", buttons: "ǁ", value: "Lateral Click", },
                { attribute: "title", buttons: "∅", value: "null", },
                { attribute: "title", buttons: "ˈ", value: "Primary Stress Mark", },
                { attribute: "title", buttons: "ˌ", value: "Secondary Stress", },
                { attribute: "title", buttons: "ː", value: "Length Mark", },
                { attribute: "title", buttons: "ˑ", value: "Half-Length", },
                { attribute: "title", buttons: "ʼ", value: "Ejective", },
                { attribute: "title", buttons: "ʴ", value: "Rhotacized", },
                { attribute: "title", buttons: "ʰ", value: "Aspirated", },
                { attribute: "title", buttons: "ʱ", value: "Breathy-Voice Aspirated", },
                { attribute: "title", buttons: "ʲ", value: "Palatalized", },
                { attribute: "title", buttons: "ʷ", value: "Labialized", },
                { attribute: "title", buttons: "ˠ", value: "Velarized", },
                { attribute: "title", buttons: "ˤ", value: "Pharyngealized", },
                { attribute: "title", buttons: "˞ ", value: "Rhotacized", },
                { attribute: "title", buttons: "̃ ", value: "Nasalized", },
                { attribute: "title", buttons: "̴ ", value: "Velarized Or Pharyngealized", },
                { attribute: "title", buttons: "̆ ", value: "Extra-Short", },
                { attribute: "title", buttons: "̈ ", value: "Centralized", },
                { attribute: "title", buttons: "̽ ", value: "Mid-Centralized", },
                { attribute: "title", buttons: "̚ ", value: "Not Audibly Released", },
                { attribute: "title", buttons: "̋ ", value: "Extra High Tone", },
                { attribute: "title", buttons: "́ ", value: "High Tone", },
                { attribute: "title", buttons: "̄ ", value: "Mid Tone", },
                { attribute: "title", buttons: "̀ ", value: "Low Tone", },
                { attribute: "title", buttons: "̏ ", value: "Extra Low Tone", },
                { attribute: "title", buttons: "̌ ", value: "Rising Tone", },
                { attribute: "title", buttons: "̂ ", value: "Falling Tone", },
                { attribute: "title", buttons: "̊ ", value: "Voiceless", },
                { attribute: "title", buttons: "̥ ", value: "Voiceless", },
                { attribute: "title", buttons: "̤ ", value: "Breathy Voiced", },
                { attribute: "title", buttons: "̪ ", value: "Dental", },
                { attribute: "title", buttons: "̬ ", value: "Voiced", },
                { attribute: "title", buttons: "̰ ", value: "Creaky Voiced", },
                { attribute: "title", buttons: "̺ ", value: "Apical", },
                { attribute: "title", buttons: "̼ ", value: "Linguolabial", },
                { attribute: "title", buttons: "̻ ", value: "Laminal", },
                { attribute: "title", buttons: "̹ ", value: "More Rounded", },
                { attribute: "title", buttons: "̜ ", value: "Less Rounded", },
                { attribute: "title", buttons: "̟ ", value: "Advanced", },
                { attribute: "title", buttons: "̠ ", value: "Retracted", },
                { attribute: "title", buttons: "̝ ", value: "Raised", },
                { attribute: "title", buttons: "̩ ", value: "Syllabic", },
                { attribute: "title", buttons: "̞ ", value: "Lowered", },
                { attribute: "title", buttons: "̯ ", value: "Non-Syllabic", },
                { attribute: "title", buttons: "̘ ", value: "Advanced Tongue Root", },
                { attribute: "title", buttons: "̙ ", value: "Retracted Tongue Root", },
            ],
            onKeyPress: function(input) {
                if (!$selectedInput) return;
                $selectedInput.val($selectedInput.val()+input);
                $selectedInput.focus();
            }
        });
    }
}